#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM="xterm-256color"
export EDITOR="/usr/bin/vim"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '[1;5D' backward-word
bindkey '[1;5C' forward-word

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

alias cp='nocorrect cp'
alias ln='nocorrect ln'
alias mv='nocorrect mv'
alias rm='nocorrect rm'
alias cpi="${aliases[cp]:-cp} -i"
alias lni="${aliases[ln]:-ln} -i"
alias mvi="${aliases[mv]:-mv} -i"
alias rmi="${aliases[rm]:-rm} -i"

alias ddrush='docker-compose exec web drush'

# Numiko drives
alias nmd=/home/craig/.local/bin/numiko-mount-drives
alias nud=/home/craig/.local/bin/numiko-umount-drives
alias nrd=/home/craig/.local/bin/numiko-remount-drives

# docker-compose
alias dcb='docker-compose build'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias dce='docker-compose exec'

# Enable|Disable Xdebug in Docker container
alias dcx-on='docker-compose exec web xdebug-switch 1 && docker-compose restart web'
alias dcx-off='docker-compose exec web xdebug-switch 0 && docker-compose restart web'

